-- 映像テロップ校閲システム / 複数運用者版
-- Supabase SQL Editor でこのファイル全体を一度実行してください。
-- 辞書のデフォルトデータは投入しません。

create extension if not exists pgcrypto;
create schema if not exists private;

-- 0. アプリ設定
create table if not exists public.app_settings (
  id int primary key default 1 check (id = 1),
  allow_registration boolean not null default true,
  updated_at timestamptz not null default now()
);
insert into public.app_settings(id, allow_registration)
values (1, true)
on conflict (id) do nothing;

-- 1. ユーザープロフィール
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text not null default '',
  role text not null default 'operator' check (role in ('admin','operator')),
  created_at timestamptz not null default now()
);

-- 2. 共有辞書
create table if not exists public.rules (
  id bigint generated by default as identity primary key,
  wrong text not null,
  correct text not null,
  enabled boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.proper_nouns (
  id bigint generated by default as identity primary key,
  variant text not null,
  canonical text not null,
  enabled boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.glyph_cautions (
  id bigint generated by default as identity primary key,
  term text not null,
  note text not null,
  enabled boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.reading_cautions (
  id bigint generated by default as identity primary key,
  term text not null,
  reading text not null,
  note text,
  enabled boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.official_name_cautions (
  id bigint generated by default as identity primary key,
  variant text not null,
  official text not null,
  note text,
  enabled boolean not null default true,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

-- 3. 運用ログ（原稿本文は保存しない）
create table if not exists public.operation_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  operator_name text not null,
  line_count int not null default 0,
  issue_count int not null default 0,
  created_at timestamptz not null default now()
);

-- 既存の試作テーブルからアップグレードする場合に備え、足りない列を補完
alter table public.rules add column if not exists created_by uuid references auth.users(id);
alter table public.proper_nouns add column if not exists created_by uuid references auth.users(id);
alter table public.operation_logs add column if not exists user_id uuid references auth.users(id);

-- 管理者判定。SECURITY DEFINER にして profiles のRLS再帰を避ける。
create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- 最初のユーザーだけ自動で admin、2人目以降は operator。
create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  initial_role text;
  registration_open boolean;
begin
  perform pg_advisory_xact_lock(78439215);

  -- 最初のユーザーは必ず作成可能。以降はアプリ設定に従う。
  if not exists (select 1 from public.profiles) then
    initial_role := 'admin';
  else
    select allow_registration into registration_open
    from public.app_settings where id = 1;

    if coalesce(registration_open, false) is not true then
      raise exception 'New user registration is closed';
    end if;
    initial_role := 'operator';
  end if;

  insert into public.profiles(id, email, display_name, role)
  values(
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'display_name', split_part(coalesce(new.email,''),'@',1)),
    initial_role
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure private.handle_new_user();

-- 辞書の created_by を自動記録
create or replace function public.set_created_by()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if new.created_by is null then
    new.created_by := auth.uid();
  end if;
  return new;
end;
$$;

drop trigger if exists rules_created_by on public.rules;
create trigger rules_created_by before insert on public.rules
for each row execute procedure public.set_created_by();

drop trigger if exists proper_nouns_created_by on public.proper_nouns;
create trigger proper_nouns_created_by before insert on public.proper_nouns
for each row execute procedure public.set_created_by();

drop trigger if exists glyph_cautions_created_by on public.glyph_cautions;
create trigger glyph_cautions_created_by before insert on public.glyph_cautions
for each row execute procedure public.set_created_by();

drop trigger if exists reading_cautions_created_by on public.reading_cautions;
create trigger reading_cautions_created_by before insert on public.reading_cautions
for each row execute procedure public.set_created_by();

drop trigger if exists official_name_cautions_created_by on public.official_name_cautions;
create trigger official_name_cautions_created_by before insert on public.official_name_cautions
for each row execute procedure public.set_created_by();

-- SECURITY DEFINER関数はAPI公開スキーマから隔離
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to authenticated;
revoke all on function private.is_admin() from public, anon;
grant execute on function private.is_admin() to authenticated;
revoke all on function private.handle_new_user() from public, anon, authenticated;

-- RLS
alter table public.app_settings enable row level security;
alter table public.profiles enable row level security;
alter table public.rules enable row level security;
alter table public.proper_nouns enable row level security;
alter table public.glyph_cautions enable row level security;
alter table public.reading_cautions enable row level security;
alter table public.official_name_cautions enable row level security;
alter table public.operation_logs enable row level security;

-- app_settings: 登録可否だけはログイン前にも読める。変更は管理者のみ。
drop policy if exists "app_settings_read_all" on public.app_settings;
create policy "app_settings_read_all"
on public.app_settings for select
to anon, authenticated
using (true);

drop policy if exists "app_settings_admin_update" on public.app_settings;
create policy "app_settings_admin_update"
on public.app_settings for update
to authenticated
using (private.is_admin())
with check (private.is_admin());

-- profiles
drop policy if exists "profiles_select_self_or_admin" on public.profiles;
create policy "profiles_select_self_or_admin"
on public.profiles for select
to authenticated
using (id = auth.uid() or private.is_admin());

drop policy if exists "profiles_update_admin" on public.profiles;
create policy "profiles_update_admin"
on public.profiles for update
to authenticated
using (private.is_admin())
with check (private.is_admin());

-- 共通辞書: ログインユーザーは読める、管理者だけ変更できる
drop policy if exists "rules_read_authenticated" on public.rules;
create policy "rules_read_authenticated" on public.rules for select to authenticated using (true);
drop policy if exists "rules_admin_insert" on public.rules;
create policy "rules_admin_insert" on public.rules for insert to authenticated with check (private.is_admin());
drop policy if exists "rules_admin_update" on public.rules;
create policy "rules_admin_update" on public.rules for update to authenticated using (private.is_admin()) with check (private.is_admin());
drop policy if exists "rules_admin_delete" on public.rules;
create policy "rules_admin_delete" on public.rules for delete to authenticated using (private.is_admin());

drop policy if exists "proper_read_authenticated" on public.proper_nouns;
create policy "proper_read_authenticated" on public.proper_nouns for select to authenticated using (true);
drop policy if exists "proper_admin_insert" on public.proper_nouns;
create policy "proper_admin_insert" on public.proper_nouns for insert to authenticated with check (private.is_admin());
drop policy if exists "proper_admin_update" on public.proper_nouns;
create policy "proper_admin_update" on public.proper_nouns for update to authenticated using (private.is_admin()) with check (private.is_admin());
drop policy if exists "proper_admin_delete" on public.proper_nouns;
create policy "proper_admin_delete" on public.proper_nouns for delete to authenticated using (private.is_admin());

drop policy if exists "glyph_read_authenticated" on public.glyph_cautions;
create policy "glyph_read_authenticated" on public.glyph_cautions for select to authenticated using (true);
drop policy if exists "glyph_admin_insert" on public.glyph_cautions;
create policy "glyph_admin_insert" on public.glyph_cautions for insert to authenticated with check (private.is_admin());
drop policy if exists "glyph_admin_update" on public.glyph_cautions;
create policy "glyph_admin_update" on public.glyph_cautions for update to authenticated using (private.is_admin()) with check (private.is_admin());
drop policy if exists "glyph_admin_delete" on public.glyph_cautions;
create policy "glyph_admin_delete" on public.glyph_cautions for delete to authenticated using (private.is_admin());

drop policy if exists "reading_read_authenticated" on public.reading_cautions;
create policy "reading_read_authenticated" on public.reading_cautions for select to authenticated using (true);
drop policy if exists "reading_admin_insert" on public.reading_cautions;
create policy "reading_admin_insert" on public.reading_cautions for insert to authenticated with check (private.is_admin());
drop policy if exists "reading_admin_update" on public.reading_cautions;
create policy "reading_admin_update" on public.reading_cautions for update to authenticated using (private.is_admin()) with check (private.is_admin());
drop policy if exists "reading_admin_delete" on public.reading_cautions;
create policy "reading_admin_delete" on public.reading_cautions for delete to authenticated using (private.is_admin());

drop policy if exists "official_read_authenticated" on public.official_name_cautions;
create policy "official_read_authenticated" on public.official_name_cautions for select to authenticated using (true);
drop policy if exists "official_admin_insert" on public.official_name_cautions;
create policy "official_admin_insert" on public.official_name_cautions for insert to authenticated with check (private.is_admin());
drop policy if exists "official_admin_update" on public.official_name_cautions;
create policy "official_admin_update" on public.official_name_cautions for update to authenticated using (private.is_admin()) with check (private.is_admin());
drop policy if exists "official_admin_delete" on public.official_name_cautions;
create policy "official_admin_delete" on public.official_name_cautions for delete to authenticated using (private.is_admin());

-- 運用ログ: 本人は自分のログ、管理者は全員分を閲覧可能
drop policy if exists "logs_select_self_or_admin" on public.operation_logs;
create policy "logs_select_self_or_admin"
on public.operation_logs for select
to authenticated
using (user_id = auth.uid() or private.is_admin());

drop policy if exists "logs_insert_self" on public.operation_logs;
create policy "logs_insert_self"
on public.operation_logs for insert
to authenticated
with check (user_id = auth.uid());

-- このMVPではログの更新・削除ポリシーを作らない（改変防止）

-- 明示的な権限付与
-- ログイン前は app_settings の登録可否だけ読める。
revoke all on table
  public.profiles,
  public.rules,
  public.proper_nouns,
  public.glyph_cautions,
  public.reading_cautions,
  public.official_name_cautions,
  public.operation_logs
from anon;

grant select on public.app_settings to anon, authenticated;
grant update on public.app_settings to authenticated;

grant select, update on public.profiles to authenticated;

grant select, insert, update, delete on public.rules to authenticated;
grant select, insert, update, delete on public.proper_nouns to authenticated;
grant select, insert, update, delete on public.glyph_cautions to authenticated;
grant select, insert, update, delete on public.reading_cautions to authenticated;
grant select, insert, update, delete on public.official_name_cautions to authenticated;

grant select, insert on public.operation_logs to authenticated;

-- identity列の採番用
grant usage, select on all sequences in schema public to authenticated;
